"use strict";
(()=>{
 const KEY="khaemenes_science_u05_v1",$=(s,p=document)=>p.querySelector(s);
 let rows=[];
 function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
 function load(){try{const s=JSON.parse(localStorage.getItem(KEY))||{};rows=Array.isArray(s.biodiversity?.rows)?s.biodiversity.rows:[];$("#datasetSource").value=s.biodiversity?.source||"";$("#surveyEffort").value=s.biodiversity?.effort||""}catch{rows=[]}if(!rows.length)for(let i=0;i<5;i++)rows.push({name:"",count:0})}
 function save(complete=false){let s;try{s=JSON.parse(localStorage.getItem(KEY))||{}}catch{s={}}s.biodiversity={complete:complete||Boolean(s.biodiversity?.complete),rows,source:$("#datasetSource").value.trim(),effort:$("#surveyEffort").value.trim(),completedAt:complete?new Date().toISOString():s.biodiversity?.completedAt};localStorage.setItem(KEY,JSON.stringify(s))}
 function render(){const body=$("#speciesRows");body.innerHTML=rows.map((r,i)=>`<tr><td><input class="species-name" data-i="${i}" value="${esc(r.name)}" aria-label="Species ${i+1} name"></td><td><input class="species-count" data-i="${i}" type="number" min="0" step="1" value="${Number(r.count)||0}" aria-label="Species ${i+1} count"></td><td><button class="btn remove-row" data-i="${i}" type="button">Remove</button></td></tr>`).join("");body.querySelectorAll(".species-name").forEach(x=>x.oninput=e=>{rows[+e.target.dataset.i].name=e.target.value;save();calculate()});body.querySelectorAll(".species-count").forEach(x=>x.oninput=e=>{rows[+e.target.dataset.i].count=Math.max(0,Math.floor(+e.target.value||0));save();calculate()});body.querySelectorAll(".remove-row").forEach(x=>x.onclick=e=>{rows.splice(+e.target.dataset.i,1);render();save();calculate()});calculate()}
 function calculate(){const valid=rows.filter(r=>r.name.trim()&&Number(r.count)>0),N=valid.reduce((a,r)=>a+Number(r.count),0),richness=valid.length;let D=0;if(N>1){const sum=valid.reduce((a,r)=>a+Number(r.count)*(Number(r.count)-1),0);D=1-sum/(N*(N-1))}$("#richness").textContent=richness;$("#totalCount").textContent=N;$("#simpson").textContent=N>1?D.toFixed(3):"—";$("#dominant").textContent=valid.length?[...valid].sort((a,b)=>b.count-a.count)[0].name:"—";return {valid,N,richness,D}}
 function complete(){const r=calculate(),source=$("#datasetSource").value.trim(),effort=$("#surveyEffort").value.trim();if(r.richness<5||!source||!effort){alert("Enter at least five species with positive counts, the data source, and sampling effort.");return}save(true);$("#completionMessage").hidden=false;$("#completionMessage").textContent="Biodiversity evidence recorded. Review sampling limits before drawing conclusions."}
 function exportData(){const r=calculate(),payload={schema:"khaemenes-biodiversity-survey-v1",source:$("#datasetSource").value.trim(),effort:$("#surveyEffort").value.trim(),rows,results:{richness:r.richness,total:r.N,simpson:r.D},exportedAt:new Date().toISOString()};const b=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="unit05-biodiversity-survey.json";a.click();URL.revokeObjectURL(u)}
 document.addEventListener("DOMContentLoaded",()=>{load();render();$("#addRow").onclick=()=>{rows.push({name:"",count:0});render()};$("#recordSurvey").onclick=complete;$("#exportSurvey").onclick=exportData;$("#datasetSource").oninput=()=>save();$("#surveyEffort").oninput=()=>save()})
})();